version: '3.1'
services:
  db:
    build: bd
    container_name: postgres-api-banking
    restart: always
    environment:
      POSTGRES_USER: apibanking
      POSTGRES_PASSWORD: 3xt4dwpb
      POSTGRES_DB:  api_banking
    ports:
      - "8285:5432"
    networks:
      - api-banking-network

  app:
    build:
      context: .
      args:
        DB_NAME: api_banking
        DB_USER: apibanking
        DB_PASSWORD: 3xt4dwpb
        DB_HOST: db
        DB_PORT: 5432
    container_name: app-api-banking
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - api-banking-network     

networks:
  api-banking-network: {}
